# Generated by Django 4.2.6 on 2023-11-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriedade',
            old_name='nome',
            new_name='nome_propriedade',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='coordenadas_geograficas',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='horario_ultima_sincronizacao',
        ),
    ]
