# Generated by Django 4.2.6 on 2023-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_nome_propriedade_nome_propriedade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='proprietarios/proprietarios/'),
        ),
    ]
